//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nhom10_QuanLyLichThiDauBongDa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CauThu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CauThu()
        {
            this.SuKienTranDaus = new HashSet<SuKienTranDau>();
        }
    
        public int MaCauThu { get; set; }
        public string HoTen { get; set; }
        public Nullable<int> Tuoi { get; set; }
        public string ViTri { get; set; }
        public Nullable<int> SoAo { get; set; }
        public Nullable<int> SoBanThang { get; set; }
        public Nullable<int> MaDoiBong { get; set; }
        public string HinhAnh { get; set; }
    
        public virtual DoiBong DoiBong { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SuKienTranDau> SuKienTranDaus { get; set; }
    }
}
