//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nhom10_QuanLyLichThiDauBongDa.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Nhom10_QuanLyBongDaEntities : DbContext
    {
        public Nhom10_QuanLyBongDaEntities()
            : base("name=Nhom10_QuanLyBongDaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CauThu> CauThus { get; set; }
        public virtual DbSet<DoiBong> DoiBongs { get; set; }
        public virtual DbSet<NguoiDung> NguoiDungs { get; set; }
        public virtual DbSet<SuKienTranDau> SuKienTranDaus { get; set; }
        public virtual DbSet<TranDau> TranDaus { get; set; }
    }
}
