//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nhom10_QuanLyLichThiDauBongDa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SuKienTranDau
    {
        public int MaSuKien { get; set; }
        public int MaTranDau { get; set; }
        public int MaCauThu { get; set; }
        public string LoaiSuKien { get; set; }
        public Nullable<int> PhutThu { get; set; }
    
        public virtual CauThu CauThu { get; set; }
        public virtual TranDau TranDau { get; set; }
    }
}
