//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nhom10_QuanLyLichThiDauBongDa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TranDau
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TranDau()
        {
            this.SuKienTranDaus = new HashSet<SuKienTranDau>();
        }
    
        public int MaTranDau { get; set; }
        public int MaDoiNha { get; set; }
        public int MaDoiKhach { get; set; }
        public System.DateTime NgayThiDau { get; set; }
        public int VongDau { get; set; }
        public Nullable<int> BanThangNha { get; set; }
        public Nullable<int> BanThangKhach { get; set; }
        public string TrangThai { get; set; }
    
        public virtual DoiBong DoiBong { get; set; }
        public virtual DoiBong DoiBong1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SuKienTranDau> SuKienTranDaus { get; set; }
    }
}
